export enum Size {
  XXS = 'XXS',
  XS = 'XS',
  S = 'S',
  M = 'M',
  L = 'L',
  XL = 'XL',
  XXL = '2XL',
  XXXL = '3XL',
  QUESTION = '?',
  FIB_1 = '1',
  FIB_2 = '2',
  FIB_3 = '3',
  FIB_5 = '5',
  FIB_8 = '8',
  FIB_13 = '13',
  FIB_21 = '21',
  FIB_34 = '34',
  FIB_55 = '55',
  FIB_89 = '89',
  MOSCOW_M = 'm',
  MOSCOW_S = 's',
  MOSCOW_C = 'c',
  MOSCOW_W = 'w'
}
